apiVersion: v1
kind: Service
metadata:
  name: nginx-headless
spec:
  clusterIP: None
  selector:
    # labels are the selectors
    project: roboshop
    component: frontend
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80 #container port
